version: "3.1"

services:

  php-fpm:
    image: webdevops/php-nginx:7.4
    container_name: exeamonitor-webserver
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app/webroot
    env_file:
      - .env
      - mysql.env
    labels:
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}'
      - 'traefik.frontend.headers.customResponseHeaders=X-Robots-Tag:noindex, nofollow, nosnippet, noarchive'
    ports: 
      - ${APP_PORT}:80

  mysql:
    image: mysql:5.6
    container_name: exeamonitor-mysql
    working_dir: /app
    volumes:
      - .:/app
      - ./data/mysql_db:/var/lib/mysql
    env_file:
      - mysql.env
    command: mysqld --character-set-server=utf8 --init-connect='SET NAMES UTF8;'

