version: "3.1"

services:

  php-fpm:
    image: webdevops/php-nginx:7.4
    container_name: exeamonitor-webserver
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app/webroot
    env_file:
      - .env
      - mysql.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.exeamonitor-webserver.rule=Host(`${PROJECT_BASE_URL}`)"
      - "traefik.http.routers.exeamonitor-webserver.tls=true"
      - "traefik.http.routers.exeamonitor-webserver.tls.certresolver=myresolver"
      - "traefik.http.routers.exeamonitor-webserever.entrypoints=web,websecure"
    ports:
      - ${APP_PORT}:80

  mysql:
    image: mysql:5.6
    container_name: exeamonitor-mysql
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
      - ./data/mysql_db:/var/lib/mysql
    env_file:
      - mysql.env
    command: mysqld --character-set-server=utf8 --init-connect='SET NAMES UTF8;'
    ports:
      - 3316:3306

  ampache:
    image: ampache/ampache:latest
    container_name: exeamonitor-ampache
    restart: unless-stopped
    volumes:
      - /home/eproductor/Music:/media
      - ./data/ampache/config:/var/www/config
      - ./data/ampache/log:/var/log/ampache
      - ./data/ampache/mysql:/var/lib/mysql
    ports:
      - 8090:80
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.exeamonitor-ampache.rule=Host(`${AMPACHE_BASE_URL}`)"
      - "traefik.http.routers.exeamonitor-ampache.tls=true"
      - "traefik.http.routers.exeamonitor-ampache.tls.certresolver=myresolver"
      - "traefik.http.routers.exeamonitor-ampache.entrypoints=web,websecure"

  cache:
    image: redis:latest
    container_name: exeamonitor-cache
    restart: unless-stopped
    volumes:
      - "./data/redis/db-data:/data"
